services:

  db:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
    image: postgis/postgis:14-3.3-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
      - traefik-proxy

  app:
    build: .
    hostname: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgis://postgres@db/postgres
      - SECRET_KEY=some-long-and-weirdly-unrandom-secret-key
      - SITE_URL=https://umap.local/
      - UMAP_ALLOW_ANONYMOUS=True
      - DEBUG=1
    volumes:
      - data:/srv/umap/uploads
      - ./:/srv/umap
    networks:
      - default
      - traefik-proxy
  
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/srv/umap/static
      - ./media:/srv/umap/media
    labels:
      - traefik.enable=true
      - traefik.http.routers.da-dev.rule=Host(`demo.kalamar.xyz`)
      - traefik.http.routers.da-dev.tls=true
      - traefik.http.routers.da-dev.tls.certresolver=le
    networks:
      - default
      - traefik-proxy
    depends_on:
      - app
    restart: always

volumes:
  data:
  db:



networks:
  traefik-proxy:
    external: true
